windowX=1500
windowY=800
gameX=86
gameY=48
nPlayers=8
maxPlayers=9
player1Name=A
player2Name=B
player3Name=C
player4Name=D
player5Name=E
player6Name=F
player7Name=G
player8Name=H
player9Name=Player 9
player1Color=255 0 0
player2Color=102 0 102
player3Color=0 255 0
player4Color=255 255 0
player5Color=0 255 255
player6Color=255 200 0
player7Color=128 128 128
player8Color=255 0 255
player9Color=0 0 0
player1Kind=AI1
player2Kind=AI2
player3Kind=AI1
player4Kind=AI2
player5Kind=AI1
player6Kind=AI2
player7Kind=AI1
player8Kind=AI2
player9Kind=HUMAN
useLastTrack=false
laps=3
